FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /ImgFormat

COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /ImgFormat
COPY --from=build-env /ImgFormat/out .
ENTRYPOINT ["dotnet", "ImgFormat.dll"]
